services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: "postgres-tutorials"
    container_name: postgres
    environment:
      POSTGRES_DB: audio_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres-audio
    volumes:
       - dbaudio:/data/postgres-audio
    ports:
      - "5432:5432"
    restart: unless-stopped
volumes:
    dbaudio:
      external: true